name: packages_videos
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  
  dio: ^4.0.6
  provider: ^6.0.4
  retrofit: ^3.3.1
  json_serializable: ^6.5.1
  json_annotation: 4.7.0

dev_dependencies:
  retrofit_generator: ^4.2.0
  build_runner: ^2.3.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
